# Generated by Django 3.2.4 on 2021-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('floor', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('isAvailable', models.BooleanField(default=False)),
            ],
        ),
    ]
