# Generated by Django 3.2.4 on 2021-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
